[05-Jan-2015 16:31:23 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:31:23 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(PDOException), Object(Symfony\Component\HttpFoundation\Request), 500)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(PDOException), Object(Symfony\Component\HttpFoundation\Request), 500)
#4 [internal function]: Silex\ExceptionListenerWrapper-> in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:31:24 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:31:24 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:31:28 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:31:28 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:31:39 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:31:39 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:31:41 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:31:41 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(PDOException), Object(Symfony\Component\HttpFoundation\Request), 500)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(PDOException), Object(Symfony\Component\HttpFoundation\Request), 500)
#4 [internal function]: Silex\ExceptionListenerWrapper-> in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:31:42 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:31:42 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:31:49 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:31:49 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:32:05 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:32:05 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:32:07 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:32:07 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:32:19 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:32:19 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(PDOException), Object(Symfony\Component\HttpFoundation\Request), 500)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(PDOException), Object(Symfony\Component\HttpFoundation\Request), 500)
#4 [internal function]: Silex\ExceptionListenerWrapper-> in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:32:19 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:32:19 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:32:22 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:32:22 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:32:26 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:32:26 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:32:31 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:32:31 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:32:34 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:32:34 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(PDOException), Object(Symfony\Component\HttpFoundation\Request), 500)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(PDOException), Object(Symfony\Component\HttpFoundation\Request), 500)
#4 [internal function]: Silex\ExceptionListenerWrapper-> in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:32:34 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:32:34 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:33:23 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:33:23 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:33:24 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:33:24 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:33:27 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:33:27 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:33:30 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:33:30 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:33:30 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:33:30 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:35:12 America/Cancun] PHP Fatal error:  Call to undefined method Silex\Application::share() in /home3/sinergi2/public_html/secsx/src/app.php on line 67
[05-Jan-2015 16:35:12 America/Cancun] PHP Fatal error:  Call to undefined method Silex\Application::share() in /home3/sinergi2/public_html/secsx/src/app.php on line 67
[05-Jan-2015 16:35:15 America/Cancun] PHP Fatal error:  Call to undefined method Silex\Application::share() in /home3/sinergi2/public_html/secsx/src/app.php on line 67
[05-Jan-2015 16:35:15 America/Cancun] PHP Fatal error:  Call to undefined method Silex\Application::share() in /home3/sinergi2/public_html/secsx/src/app.php on line 67
[05-Jan-2015 16:35:16 America/Cancun] PHP Fatal error:  Call to undefined method Silex\Application::share() in /home3/sinergi2/public_html/secsx/src/app.php on line 67
[05-Jan-2015 16:35:30 America/Cancun] PHP Fatal error:  Call to undefined method Silex\Application::share() in /home3/sinergi2/public_html/secsx/src/app.php on line 67
[05-Jan-2015 16:35:30 America/Cancun] PHP Fatal error:  Call to undefined method Silex\Application::share() in /home3/sinergi2/public_html/secsx/src/app.php on line 67
[05-Jan-2015 16:36:48 America/Cancun] PHP Fatal error:  Call to undefined method Silex\Application::share() in /home3/sinergi2/public_html/secsx/src/app.php on line 67
[05-Jan-2015 16:36:49 America/Cancun] PHP Fatal error:  Call to undefined method Silex\Application::share() in /home3/sinergi2/public_html/secsx/src/app.php on line 67
[05-Jan-2015 16:37:18 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:37:18 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:37:18 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:37:18 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:37:21 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:37:21 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:37:24 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:37:24 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:37:24 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:37:24 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:37:36 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:37:36 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:37:42 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:37:42 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:37:45 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:37:45 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:37:46 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:37:46 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
[05-Jan-2015 16:37:48 America/Cancun] PHP Notice:  Object of class Symfony\Component\HttpFoundation\Request could not be converted to int in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 468
[05-Jan-2015 16:37:48 America/Cancun] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The HTTP status code "1" is not valid.' in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:470
Stack trace:
#0 /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(203): Symfony\Component\HttpFoundation\Response->setStatusCode(Object(Symfony\Component\HttpFoundation\Request))
#1 /home3/sinergi2/public_html/secsx/src/controllers.php(157): Symfony\Component\HttpFoundation\Response->__construct('<!DOCTYPE html>...', Object(Symfony\Component\HttpFoundation\Request))
#2 [internal function]: {closure}(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\Component\HttpFoundation\Request), 404)
#3 /home3/sinergi2/public_html/secsx/vendor/silex/silex/src/Silex/ExceptionListenerWrapper.php(53): call_user_func(Object(Closure), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException), Object(Symfony\ in /home3/sinergi2/public_html/secsx/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php on line 470
